// web/src/lib/components/sites/SiteCard.svelte
<script lang="ts">
	import type { Site } from '$api/types';
	import StatusDot from '$components/ui/StatusDot.svelte';
	import Badge from '$components/ui/Badge.svelte';
	import { Code, ExternalLink } from 'lucide-svelte';
	import { timeAgo } from '$lib/utils/time';
	import { getInstanceDomain } from '$lib/utils/config';

	interface Props {
		site: Site;
	}

	let { site }: Props = $props();

	const domain = getInstanceDomain();
	let status = $derived(site.active_version !== null ? 'live' as const : 'empty' as const);
	let siteUrl = $derived(`https://${site.subdomain_slug}.${domain}`);
</script>

<a
	href="/sites/{site.id}"
	class="group block rounded-xl border border-border bg-surface p-4 transition-all hover:border-primary/30 hover:bg-elevated/50 hover:shadow-lg hover:shadow-primary/5"
>
	<div class="flex items-start justify-between mb-2">
		<div class="flex items-center gap-2 min-w-0">
			<StatusDot {status} />
			<span class="font-semibold text-text truncate">{site.name}</span>
		</div>
		{#if site.active_version !== null}
			<Badge variant="success">v{site.active_version}</Badge>
		{/if}
	</div>

	<div class="flex items-center gap-1 mb-3">
		<span class="text-xs font-mono text-text-muted truncate">{site.subdomain_slug}.{domain}</span>
		<ExternalLink class="size-3 text-text-muted shrink-0 opacity-0 group-hover:opacity-100 transition-opacity" />
	</div>

	<div class="flex items-center gap-3 text-xs text-text-muted">
		{#if site.has_worker}
			<span class="inline-flex items-center gap-1 text-info">
				<Code class="size-3" />
				Worker
			</span>
		{/if}
		{#if site.spa_mode}
			<Badge variant="outline">SPA</Badge>
		{/if}
		<span class="ml-auto">{timeAgo(site.created_at)}</span>
	</div>
</a>

// web/src/components/sites/site-card.tsx
import { Link } from "react-router-dom"
import { ExternalLink } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import type { Site } from "@/types/api"

interface SiteCardProps {
  site: Site
  domain: string
}

export function SiteCard({ site, domain }: SiteCardProps) {
  const hasDeployment = site.active_version !== null

  return (
    <Link
      to={`/sites/${site.id}`}
      className="group block rounded-lg border border-border bg-card p-4 transition-colors hover:border-muted-foreground/30"
    >
      <div className="flex items-start justify-between">
        <div className="min-w-0">
          <h3 className="font-medium truncate">{site.name}</h3>
          <div className="flex items-center gap-1.5 mt-1">
            <span className="text-xs text-muted-foreground font-mono truncate">
              {site.subdomain_slug}.{domain}
            </span>
            {hasDeployment && (
              <ExternalLink className="size-3 text-muted-foreground opacity-0 group-hover:opacity-100 transition-opacity" />
            )}
          </div>
        </div>
        <Badge variant={hasDeployment ? "default" : "secondary"} className="ml-2 shrink-0">
          {hasDeployment ? `v${site.active_version}` : "no deploys"}
        </Badge>
      </div>
      <p className="text-xs text-muted-foreground mt-3">
        {new Date(site.created_at).toLocaleDateString()}
      </p>
    </Link>
  )
}
