// web/src/lib/components/sites/SiteSettings.svelte
<script lang="ts">
	import type { Site } from '$api/types';
	import { sites } from '$api/client';
	import Button from '$components/ui/Button.svelte';
	import Input from '$components/ui/Input.svelte';
	import { Loader2, Trash2 } from 'lucide-svelte';
	import { goto } from '$app/navigation';

	interface Props {
		site: Site;
		onUpdated: () => void;
	}

	let { site, onUpdated }: Props = $props();

	let name = $state(site.name);
	let spaMode = $state(site.spa_mode);
	let saving = $state(false);
	let deleting = $state(false);
	let confirmDelete = $state('');
	let error = $state('');

	async function handleSave() {
		saving = true;
		error = '';
		try {
			await sites.update(site.id, { name, spa_mode: spaMode });
			onUpdated();
		} catch (err) {
			error = err instanceof Error ? err.message : 'Failed to update';
		} finally {
			saving = false;
		}
	}

	async function handleDelete() {
		if (confirmDelete !== site.subdomain_slug) return;
		deleting = true;
		try {
			await sites.delete(site.id);
			goto('/');
		} catch (err) {
			error = err instanceof Error ? err.message : 'Failed to delete';
			deleting = false;
		}
	}
</script>

<div class="space-y-8 max-w-lg">
	<!-- General settings -->
	<div class="space-y-4">
		<h3 class="text-lg font-semibold">General</h3>

		<div class="space-y-1.5">
			<label for="site-name" class="text-sm font-medium text-text">Site name</label>
			<Input id="site-name" bind:value={name} />
		</div>

		<div class="flex items-center gap-3">
			<input
				type="checkbox"
				id="spa-mode"
				bind:checked={spaMode}
				class="rounded border-border accent-primary"
			/>
			<label for="spa-mode" class="text-sm text-text">SPA mode</label>
			<span class="text-xs text-text-muted">(Route all paths to index.html)</span>
		</div>

		{#if error}
			<p class="text-sm text-error">{error}</p>
		{/if}

		<Button onclick={handleSave} disabled={saving}>
			{#if saving}
				<Loader2 class="size-4 animate-spin" />
				Saving...
			{:else}
				Save changes
			{/if}
		</Button>
	</div>

	<!-- Danger zone -->
	<div class="rounded-xl border border-error/30 p-4 space-y-3">
		<h3 class="text-lg font-semibold text-error">Danger zone</h3>
		<p class="text-sm text-text-muted">
			Type <code class="font-mono text-xs bg-elevated px-1.5 py-0.5 rounded">{site.subdomain_slug}</code> to confirm deletion.
		</p>
		<Input
			placeholder={site.subdomain_slug}
			bind:value={confirmDelete}
			class="font-mono text-xs"
		/>
		<Button
			variant="danger"
			onclick={handleDelete}
			disabled={confirmDelete !== site.subdomain_slug || deleting}
		>
			{#if deleting}
				<Loader2 class="size-4 animate-spin" />
				Deleting...
			{:else}
				<Trash2 class="size-4" />
				Delete site
			{/if}
		</Button>
	</div>
</div>

// web/src/components/sites/site-settings.tsx
import { useState, type FormEvent } from "react"
import { useNavigate } from "react-router-dom"
import { toast } from "sonner"
import { Loader2 } from "lucide-react"
import { sites } from "@/lib/api"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
import { Separator } from "@/components/ui/separator"
import { ConfirmDialog } from "@/components/shared/confirm-dialog"
import type { Site } from "@/types/api"

interface SiteSettingsProps {
  site: Site
  onUpdated: () => void
}

export function SiteSettings({ site, onUpdated }: SiteSettingsProps) {
  const navigate = useNavigate()
  const [name, setName] = useState(site.name)
  const [spaMode, setSpaMode] = useState(site.spa_mode)
  const [saving, setSaving] = useState(false)
  const [deleteOpen, setDeleteOpen] = useState(false)
  const [deleting, setDeleting] = useState(false)

  async function handleSave(e: FormEvent) {
    e.preventDefault()
    setSaving(true)
    try {
      await sites.update(site.id, { name, spa_mode: spaMode })
      toast.success("Settings saved")
      onUpdated()
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Failed to save")
    } finally {
      setSaving(false)
    }
  }

  async function handleDelete() {
    setDeleting(true)
    try {
      await sites.delete(site.id)
      toast.success("Site deleted")
      navigate("/")
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Failed to delete")
      setDeleting(false)
    }
  }

  return (
    <div className="space-y-6">
      <form onSubmit={handleSave} className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="site-name">Site name</Label>
          <Input
            id="site-name"
            value={name}
            onChange={(e) => setName(e.target.value)}
            required
          />
        </div>

        <div className="flex items-center justify-between">
          <div>
            <Label htmlFor="spa-mode">SPA mode</Label>
            <p className="text-xs text-muted-foreground mt-0.5">
              Serve index.html for all routes (single-page app)
            </p>
          </div>
          <Switch
            id="spa-mode"
            checked={spaMode}
            onCheckedChange={setSpaMode}
          />
        </div>

        <Button type="submit" disabled={saving}>
          {saving ? <Loader2 className="size-4 animate-spin" /> : "Save changes"}
        </Button>
      </form>

      <Separator />

      <div>
        <h3 className="text-sm font-medium text-destructive">Danger zone</h3>
        <p className="text-xs text-muted-foreground mt-1">
          Permanently delete this site and all its deployments.
        </p>
        <Button
          variant="destructive"
          size="sm"
          className="mt-3"
          onClick={() => setDeleteOpen(true)}
          disabled={deleting}
        >
          {deleting ? <Loader2 className="size-4 animate-spin" /> : "Delete site"}
        </Button>
      </div>

      <ConfirmDialog
        open={deleteOpen}
        onOpenChange={setDeleteOpen}
        title="Delete site"
        description={`This will permanently delete "${site.name}" and all its deployments. This action cannot be undone.`}
        confirmLabel="Delete"
        onConfirm={handleDelete}
        destructive
      />
    </div>
  )
}
