// web/src/components/sites/create-site-dialog.tsx
import { useState, type FormEvent } from "react"
import { toast } from "sonner"
import { Loader2 } from "lucide-react"
import { sites } from "@/lib/api"
import { getInstanceDomain } from "@/lib/config"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"

interface CreateSiteDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  onCreated: () => void
}

export function CreateSiteDialog({ open, onOpenChange, onCreated }: CreateSiteDialogProps) {
  const [name, setName] = useState("")
  const [slug, setSlug] = useState("")
  const [loading, setLoading] = useState(false)

  async function handleSubmit(e: FormEvent) {
    e.preventDefault()
    setLoading(true)
    try {
      await sites.create(name, slug || undefined)
      toast.success("Site created")
      setName("")
      setSlug("")
      onOpenChange(false)
      onCreated()
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Failed to create site")
    } finally {
      setLoading(false)
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>New site</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="site-name">Name</Label>
            <Input
              id="site-name"
              placeholder="My Portfolio"
              value={name}
              onChange={(e) => setName(e.target.value)}
              required
              autoFocus
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="site-slug">Subdomain (optional)</Label>
            <div className="flex items-center gap-2">
              <Input
                id="site-slug"
                placeholder="my-portfolio"
                value={slug}
                onChange={(e) => setSlug(e.target.value)}
                className="font-mono text-sm"
              />
              <span className="text-sm text-muted-foreground whitespace-nowrap">.{getInstanceDomain()}</span>
            </div>
            <p className="text-xs text-muted-foreground">
              Leave blank to auto-generate from name
            </p>
          </div>
          <Button
            type="submit"
            className="w-full bg-emerald-600 text-white hover:bg-emerald-500"
            disabled={loading}
          >
            {loading ? <Loader2 className="size-4 animate-spin" /> : "Create site"}
          </Button>
        </form>
      </DialogContent>
    </Dialog>
  )
}

// web/src/lib/components/sites/CreateSiteDialog.svelte
<script lang="ts">
	import { sites } from '$api/client';
	import Dialog from '$components/ui/Dialog.svelte';
	import Button from '$components/ui/Button.svelte';
	import Input from '$components/ui/Input.svelte';
	import { Loader2 } from 'lucide-svelte';

	interface Props {
		open: boolean;
		onClose: () => void;
		onCreated: () => void;
	}

	let { open, onClose, onCreated }: Props = $props();

	let name = $state('');
	let slug = $state('');
	let loading = $state(false);
	let error = $state('');

	async function handleSubmit(e: SubmitEvent) {
		e.preventDefault();
		loading = true;
		error = '';
		try {
			await sites.create(name, slug || undefined);
			name = '';
			slug = '';
			onCreated();
			onClose();
		} catch (err) {
			error = err instanceof Error ? err.message : 'Failed to create site';
		} finally {
			loading = false;
		}
	}
</script>

<Dialog {open} {onClose} title="Create new site">
	<form onsubmit={handleSubmit} class="space-y-4">
		<div class="space-y-1.5">
			<label for="site-name" class="text-sm font-medium text-text">Name</label>
			<Input
				id="site-name"
				placeholder="My Site"
				bind:value={name}
				required
				autofocus
			/>
		</div>

		<div class="space-y-1.5">
			<label for="site-slug" class="text-sm font-medium text-text">Subdomain</label>
			<Input
				id="site-slug"
				placeholder="my-site (optional, auto-generated)"
				bind:value={slug}
				class="font-mono text-xs"
			/>
			<p class="text-xs text-text-muted">Leave blank to auto-generate from name</p>
		</div>

		{#if error}
			<p class="text-sm text-error">{error}</p>
		{/if}

		<div class="flex justify-end gap-2 pt-2">
			<Button variant="ghost" type="button" onclick={onClose}>Cancel</Button>
			<Button type="submit" disabled={loading}>
				{#if loading}
					<Loader2 class="size-4 animate-spin" />
					Creating...
				{:else}
					Create site
				{/if}
			</Button>
		</div>
	</form>
</Dialog>
