// web/src/components/shared/page-header.tsx
import type { ReactNode } from "react"

interface PageHeaderProps {
  title: string
  description?: string
  action?: ReactNode
}

export function PageHeader({ title, description, action }: PageHeaderProps) {
  return (
    <div className="flex items-center justify-between mb-6">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">{title}</h1>
        {description && (
          <p className="text-sm text-muted-foreground mt-1">{description}</p>
        )}
      </div>
      {action && <div>{action}</div>}
    </div>
  )
}

// web/src/lib/components/shared/PageHeader.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	interface Props {
		title: string;
		description?: string;
		action?: Snippet;
	}

	let { title, description, action }: Props = $props();
</script>

<div class="flex items-center justify-between pb-4 border-b border-border mb-6">
	<div>
		<h1 class="text-2xl font-bold tracking-tight text-text">{title}</h1>
		{#if description}
			<p class="text-sm text-text-muted mt-0.5">{description}</p>
		{/if}
	</div>
	{#if action}
		{@render action()}
	{/if}
</div>
